name: new_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  provider: ^6.1.2
  go_router: ^14.0.2
  get_it: ^7.7.0
  injectable: ^2.4.1
  http:
  json_serializable: ^6.7.1
  http_interceptor: ^1.0.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  json_serializable: ^6.7.1


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

